name: Terraform CI/CD Workflow

on:
  push:
    branches:
      - main  # Thực hiện khi có thay đổi trên nhánh main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Cài đặt Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Thay bằng phiên bản Terraform bạn sử dụng

    # 3. Kiểm tra mã nguồn Terraform với Checkov
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .  # Thư mục chứa các file Terraform

    # 4. Khởi tạo Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Kiểm tra kế hoạch triển khai Terraform
    - name: Terraform Plan
      run: terraform plan

    # 6. Triển khai Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
